[target.aarch64-linux-android]
linker = "/home/Prslc/toolchain/NDK/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang"

[env]
CC_aarch64_linux_android = "/home/Prslc/toolchain/NDK/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang"
CXX_aarch64_linux_android = "/home/Prslc/toolchain/NDK/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang++"
AR_aarch64_linux_android = "/home/Prslc/toolchain/NDK/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"